#:schema = "https://developers.openai.com/codex/config-schema.json"
model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"
model_instructions_file = "/Users/kcw/GitHub/dotfiles/AGENTS.md"

[marketplaces.openai-bundled]
last_updated = "2026-07-08T15:09:07Z"
source_type = "local"
source = "/Users/kcw/Github/dotfiles/main/.config/codex/.tmp/bundled-marketplaces/openai-bundled"

[features]
js_repl = false

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/kcw/.config/codex"
CODEX_HOME = "/Users/kcw/.config/codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "97669f77b3ca7114a2df05d55646416ea34b28100c07213ef9f643803449ef2f"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.623.141536"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"
